apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
      - name: petclinic
        image: 257307634175.dkr.ecr.ap-northeast-2.amazonaws.com/project05-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-service
spec:
  type: NodePort
  selector:
    app: pet-clinic
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 80
      targetPort: 8080
